### ISSUE TITLE
Symphytum

### ISSUE THREAD

**Issue by benj-d** [burkmarr/Gilbert21#1]
When using Atlas taxonomy search to find _Symphytum_ the returned taxon tree appears to fall down (no option is returned). If _Symphytum officinale_ is searched for then the species is not returned but the tree returns any sub taxa that contain _officinale_ on the genus search it appears to fail at Magnoliopsida.

![genus](https://cloud.githubusercontent.com/assets/7861877/25489533/009e4e60-2b62-11e7-816a-8a2215dc9af4.png)
![officinale](https://cloud.githubusercontent.com/assets/7861877/25489534/00aa65d8-2b62-11e7-9a0c-6924c0142c7b.png)

I checked the species names, both genus and bionomial are correct and on the Atlas.

However, if potential relevance, when searching using your taxonomy visualiser the genus entry is returned as **Symphytum (indet. Comfrey)**
![vis](https://cloud.githubusercontent.com/assets/7861877/25489661/6c544416-2b62-11e7-8fde-13db4e4344e3.png)

Are the indet. brackets breaking the Gilbert21?

**Comment by burkmarr** [comment]
It certainly looks that way from your analysis Ben. I will aim look into it further over the week and update you.

**Comment by burkmarr** [comment]
Hi Ben. I've found the source of the problem with this: the Atlas taxonomy for _Symphytum_ goes straight from class to family and skips order. This caught the G21 code (i.e. me!) by surprise. 

I can fix that easily enough, but in the course of investigating it, I've realised that the new taxon tree isn't very helpful for selecting higher level taxa. For example if you do a search on any genus (one that works), the results list the genus and, under it, the species, but you can't click on the genus and get it to fill in the name for you. So I'm going to do a bit more work on this yet before releasing a fix.

**Comment by burkmarr** [comment]
This is now fixed in release 3.2.1. Also improved some features of the way that matching results are displayed to users.

**Comment by burkmarr** [comment]
Hi Ben,

You've probably had a GitHub notification, but just to let you know that
this is done now.

I have your Spider book here. (It's superb - you will love it!) We go on
holiday on Saturday, but I'll be around on Friday evening if you wanted to
drop by for a cup of tea and to collect it from work. Otherwise, I'll give
it to you when we meet up later in June.

Rich
