### ISSUE TITLE
Google Maps don't work

### ISSUE THREAD

**Issue by burkmarr** [burkmarr/Gilbert21#4]
A post from the G21 fb page and my response on 14th Oct 2018.

>>>
"Hi Rich, something odd started over last few weeks. Trying to use GM in PC software gives me an error message "...403 ..forbidden.. max number of requests exceeded in 24 hr period.. please try later"  I am able to use Bing successfully instead but wondered if it was possible to fix the Google Maps problem? Thanks. Jim"

>>>
"Hi Jim. It looks as though GM has stopped working - presumably because Google have changed the API. G21 assumes that an error retrieving the Google map is due to the download limitation, but clearly here it isn't. A change in the API will require an update to the G21 software and a new release in order to fix. I will log this as an issue, but I can't say when I will be able to address it. So in the meantime, you'll need to rely on Bing if you need this feature."

**Comment by benj-d** [comment]
added key in branch tb sync'd.

**Comment by burkmarr** [comment]
@benj-d - did you have to register a card to get this key?

**Comment by benj-d** [comment]
Already registered as use APIs for MBB work. I can monitor use on console and will set up an oauth so it's use is limited to the app.
